"""
NetArchitect AI: Vendor Configuration Engine
Generates deterministic, vendor-specific CLI configuration scripts strictly
matching node CLI types from device_catalog.yaml:
- vyos: Declarative set/commit operational commands
- vtysh: Cisco-like router configuration blocks for FRRouting
- openflow: Open vSwitch shell scripts (ovs-vsctl)
- bash: Alpine Linux network interface scripts & iptables firewall policies
"""
from typing import Dict, Any, List, Optional


class ConfigEngine:
    @staticmethod
    def generate_vyos(
        hostname: str,
        mgmt_ip: str,
        interfaces: List[Dict[str, Any]],
        dhcp_pools: Optional[List[Dict[str, Any]]] = None,
        nat_rules: Optional[List[Dict[str, Any]]] = None,
        static_routes: Optional[List[Dict[str, Any]]] = None,
        ospf_areas: Optional[List[Dict[str, Any]]] = None
    ) -> str:
        """Renders VyOS 1.4 Rolling declarative configuration commands."""
        lines = [
            f"# VyOS 1.4 Rolling Router Configuration: {hostname}",
            "# Generated by NetArchitect AI Configuration Engine",
            "",
            f"set system host-name '{hostname}'",
            "set system domain-name 'lab.local'",
            "",
            "# OOB Management Plane",
            f"set interfaces ethernet eth0 description 'OOB Management Plane'",
            f"set interfaces ethernet eth0 address '{mgmt_ip}/24'",
            ""
        ]

        # Interfaces & 802.1Q sub-interfaces
        for iface in interfaces:
            name = iface.get("name")
            if name == "eth0":
                continue
            desc = iface.get("description", "Data Port")
            lines.append(f"set interfaces ethernet {name} description '{desc}'")

            vifs = iface.get("vifs", [])
            for vif in vifs:
                vlan_id = vif.get("vlan")
                ip = vif.get("ip")
                vdesc = vif.get("description", f"VLAN {vlan_id}")
                lines.append(f"set interfaces ethernet {name} vif {vlan_id} description '{vdesc}'")
                lines.append(f"set interfaces ethernet {name} vif {vlan_id} address '{ip}'")

        # DHCP Pools
        if dhcp_pools:
            lines.append("\n# DHCP Service Pools")
            for pool in dhcp_pools:
                name = pool.get("name", "POOL")
                subnet = pool.get("subnet")
                gw = pool.get("default_router")
                start = pool.get("range_start")
                stop = pool.get("range_stop")
                dns = pool.get("dns", ["1.1.1.1", "8.8.8.8"])

                lines.append(f"set service dhcp-server shared-network-name {name} authoritative")
                lines.append(f"set service dhcp-server shared-network-name {name} subnet {subnet} default-router '{gw}'")
                for d in dns:
                    lines.append(f"set service dhcp-server shared-network-name {name} subnet {subnet} name-server '{d}'")
                lines.append(f"set service dhcp-server shared-network-name {name} subnet {subnet} range 0 start '{start}'")
                lines.append(f"set service dhcp-server shared-network-name {name} subnet {subnet} range 0 stop '{stop}'")

        # NAT Rules
        if nat_rules:
            lines.append("\n# NAT Masquerade Policies")
            for rule in nat_rules:
                rid = rule.get("id", 100)
                src = rule.get("source_subnet")
                out_if = rule.get("outbound_if", "eth0")
                lines.append(f"set nat source rule {rid} description 'Outbound NAT'")
                lines.append(f"set nat source rule {rid} source address '{src}'")
                lines.append(f"set nat source rule {rid} outbound-interface '{out_if}'")
                lines.append(f"set nat source rule {rid} translation address 'masquerade'")

        # Static Routes
        if static_routes:
            lines.append("\n# Static Routing")
            for r in static_routes:
                prefix = r.get("prefix", "0.0.0.0/0")
                nh = r.get("next_hop")
                lines.append(f"set protocols static route {prefix} next-hop {nh}")

        # OSPF
        if ospf_areas:
            lines.append("\n# OSPF Dynamic Routing")
            for a in ospf_areas:
                area_id = a.get("area", "0")
                for net in a.get("networks", []):
                    lines.append(f"set protocols ospf area {area_id} network '{net}'")

        lines.extend([
            "",
            "set service ssh port '22'",
            f"set service ssh listen-address '{mgmt_ip}'",
            "",
            "commit",
            "save"
        ])
        return "\n".join(lines)

    @staticmethod
    def generate_ovs(
        hostname: str,
        mgmt_ip: str,
        bridge_name: str = "br-lab",
        trunk_ports: Optional[List[str]] = None,
        access_ports: Optional[List[Dict[str, Any]]] = None
    ) -> str:
        """Renders Open vSwitch shell provisioning script."""
        lines = [
            "#!/bin/sh",
            f"# Open vSwitch Layer 2/3 Configuration: {hostname}",
            "# Generated by NetArchitect AI Configuration Engine",
            "",
            "/etc/init.d/openvswitch-switch start 2>/dev/null || true",
            f"ovs-vsctl --if-exists del-br {bridge_name}",
            f"ovs-vsctl add-br {bridge_name}",
            ""
        ]

        if trunk_ports:
            lines.append("# 802.1Q Trunk Ports")
            for port in trunk_ports:
                lines.append(f"ovs-vsctl add-port {bridge_name} {port}")
                lines.append(f"ip link set {port} up")

        if access_ports:
            lines.append("\n# Access Ports with Explicit 802.1Q Tagging")
            for p in access_ports:
                port = p.get("port")
                vlan = p.get("vlan")
                lines.append(f"ovs-vsctl add-port {bridge_name} {port} tag={vlan}")
                lines.append(f"ip link set {port} up")

        lines.extend([
            "",
            f"ip link set {bridge_name} up",
            "",
            "# OOB Management Plane",
            "ovs-vsctl --if-exists del-br br-mgmt",
            "ovs-vsctl add-br br-mgmt",
            f"ip addr add {mgmt_ip}/24 dev br-mgmt 2>/dev/null || true",
            "ip link set br-mgmt up",
            "",
            f'echo "{hostname} configuration successfully applied."'
        ])
        return "\n".join(lines)

    @staticmethod
    def generate_alpine(
        hostname: str,
        ip_address: str,
        gateway: str,
        dns: Optional[List[str]] = None
    ) -> str:
        """Renders Alpine Linux Workstation configuration."""
        dns_servers = dns or ["1.1.1.1", "8.8.8.8"]
        dns_lines = "\n".join([f'echo "nameserver {d}" >> /etc/resolv.conf' for d in dns_servers])

        script = f"""#!/bin/sh
# Alpine Linux Workstation Configuration: {hostname}
# Generated by NetArchitect AI Configuration Engine

hostname {hostname}
echo "{hostname}" > /etc/hostname

cat << 'EOF' > /etc/network/interfaces
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
    address {ip_address}
    netmask 255.255.255.0
    gateway {gateway}
EOF

echo "nameserver {dns_servers[0]}" > /etc/resolv.conf
{dns_lines}

ifdown eth0 2>/dev/null || true
ifup eth0

echo "{hostname} network configuration initialized."
"""
        return script
